version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      SECRET_KEY: your_secret_key
      DATABASE_URL: postgresql://admindev:admindev@db:5432/jp_funding_rate
    depends_on:
      - db
    dns:
      - 1.1.1.1
      - 1.0.0.1

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: jp_funding_rate
      POSTGRES_USER: admindev
      POSTGRES_PASSWORD: admindev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    dns:
      - 1.1.1.1
      - 1.0.0.1

volumes:
  postgres_data:
