import json

def load_tickers(platform):
    with open("ticker.json", 'r') as f:
        data = json.load(f)
    return data[platform]

def get_logo_url(ticker_symbol):
    name_mappings = {
        '10000SATS': 'bitcoin',
        '1000BONK': 'bonk',
        '1000PEPE': 'pepecoin',
        'AEVO': 'aevo',
        'ALT': 'altcoin',
        'APT': 'aptos',
        'AR': 'arweave',
        'ARB': 'arbitrum',
        'ATOM': 'cosmos',
        'AVAX': 'avalanche',
        'AXL': 'axelar',
        'BEAMX': 'beam',
        'BITCOIN': 'bitcoin',
        'BLAST': 'blast',
        'BLUR': 'blur',
        'BLZ': 'bluzelle',
        'BNB': 'binance-coin',
        'BTC': 'bitcoin',
        'CANTO': 'canto',
        'CRV': 'curve',
        'DOGE': 'dogecoin',
        'DYDX': 'dydx',
        'DYM': 'dym',
        'ENA': 'ena',
        'ETH': 'ethereum',
        'ETHFI': 'ethfi',
        'FTM': 'fantom',
        'GLMR': 'glimmer',
        'HIFI': 'hifi',
        'HPOS': 'hpos',
        'ILV': 'illuvium',
        'INJ': 'injective',
        'JITO': 'jito',
        'JUP': 'jupiter',
        'LDO': 'lido',
        'LINK': 'chainlink',
        'MANTA': 'mantle',
        'MATIC': 'polygon',
        'MEME': 'meme',
        'MERL': 'merlin',
        'MINA': 'mina',
        'MKR': 'maker',
        'MYRO': 'myro',
        'NEAR': 'near',
        'NMR': 'numeraire',
        'NTRN': 'ntrn',
        'OMNI': 'omni',
        'OP': 'optimism',
        'ORDI': 'ordi',
        'OX': 'ox',
        'PARCL': 'parcl',
        'PENDLE': 'pendle',
        'PIXEL': 'pixel',
        'PORTAL': 'portal',
        'PRIME': 'prime',
        'PYTH': 'pyth',
        'SAGA': 'saga',
        'SEI': 'sei',
        'SHFL': 'shfl',
        'SLERF': 'slerf',
        'SOL': 'solana',
        'STRK': 'strike',
        'SUI': 'sui',
        'SYN': 'syn',
        'T': 'threshold',
        'TAO': 'tao',
        'TIA': 'tia',
        'TNSR': 'tnsr',
        'TON': 'toncoin',
        'TRB': 'tellor',
        'TRX': 'tron',
        'UMA': 'uma',
        'W': 'w',
        'WIF': 'wif',
        'WLD': 'wld',
        'XRP': 'ripple',
        'ZERO': 'zero',
        'ZETA': 'zeta',
        # Add more mappings as needed
    }
    name = name_mappings.get(ticker_symbol.upper())
    if name:
        return f"https://cryptologos.cc/logos/{name}-{ticker_symbol.lower()}-logo.png"
    else:
        return None